# Generated by Django 4.2.3 on 2024-02-12 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('Departamento', models.CharField(max_length=250, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='static/img/noticias')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='tipo_contratos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('contrato', models.CharField(max_length=250, verbose_name='Tipo de contrato')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipo de Contrato',
            },
        ),
        migrations.CreateModel(
            name='ubicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('ubicacion', models.CharField(max_length=250, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciónes',
            },
        ),
        migrations.CreateModel(
            name='puesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('Puesto', models.CharField(max_length=250, verbose_name='Puesto')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='intranet.departamento')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Código')),
                ('fecha_alta', models.DateField(verbose_name='Fecha Alta')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('apellido_paterno', models.CharField(max_length=250, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=250, verbose_name='Apellido Materno')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('correo_instucional', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Correo Lazzar')),
                ('correo_nomina', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Correo')),
                ('codigo_jefe', models.IntegerField(default=0, verbose_name='Código Jefe Inmediato')),
                ('jefe', models.CharField(max_length=250, verbose_name='Jefe Inmediato')),
                ('baja', models.BooleanField(default=False, verbose_name='¿Es Baja?')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha Baja')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Ultima Modificación')),
                ('fecha_cumpleaños', models.DateField(blank=True, null=True, verbose_name='Fecha Cumpleaños')),
                ('correo_cumple_enviado', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_de_contrato', to='intranet.tipo_contratos')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamento', to='intranet.departamento')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puesto', to='intranet.puesto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centro_de_trabajo_empleados', to='intranet.ubicacion')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='DiasProgramadasVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_final', models.DateField(verbose_name='Fecha de Finalización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('prog_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prog_empleado', to='intranet.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='dias_disponibles_vacaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('saldo_anterior', models.IntegerField(default=0, verbose_name='Saldo año anterior')),
                ('dias_vacaciones', models.IntegerField(default=0, verbose_name='Días de vacaciones')),
                ('semana_santa', models.IntegerField(default=6, verbose_name='Semana Santa')),
                ('saldo_actual', models.IntegerField(default=0, verbose_name='Saldo actual')),
                ('programados', models.IntegerField(default=0, verbose_name='Días programados')),
                ('dias_tomados', models.IntegerField(default=0, verbose_name='Días tomados')),
                ('saldo_final', models.IntegerField(default=0, verbose_name='Saldo final')),
                ('dato_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dato_empleado', to='intranet.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='bono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('Año', models.IntegerField(default=2024, verbose_name='Año')),
                ('Mes', models.IntegerField(default=0, verbose_name='Mes')),
                ('Quincena', models.IntegerField(default=0, verbose_name='Quincena')),
                ('Calificacion', models.IntegerField(default=0, verbose_name='Calificación')),
                ('cal_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cal_empleado', to='intranet.empleados', unique=True)),
            ],
            options={
                'verbose_name': 'Bono',
            },
        ),
    ]
