# Generated by Django 5.0.2 on 2024-02-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='correo_aniversario_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
