# Generated by Django 4.2.6 on 2024-02-20 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_empleados_correo_aniversario_enviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bono',
            name='cal_empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cal_empleado', to='intranet.empleados', verbose_name='Empleado'),
        ),
    ]
