# Generated by Django 5.0.1 on 2024-02-20 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_empleados_correo_aniversario_enviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bono',
            name='cal_empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cal_empleado', to='intranet.empleados', verbose_name='Empleado'),
        ),
    ]
