# Generated by Django 4.2.3 on 2023-08-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_correoslazzar_admin_group_correoslazzar_cod_proscai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoslazzar',
            name='vender_group',
            field=models.BooleanField(default=True, verbose_name='Vendedor Solo?'),
        ),
    ]
