# Generated by Django 4.2.2 on 2023-09-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_correoslazzar_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correoslazzar',
            name='cod_Proscai',
            field=models.CharField(default='', max_length=4, verbose_name='Codigo Proscai'),
        ),
    ]
