# Generated by Django 4.2.6 on 2024-02-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_correoslazzar_num_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoslazzar',
            name='num_empleado',
            field=models.IntegerField(default=0, verbose_name='Código Empleado'),
        ),
    ]
