# Generated by Django 4.2.6 on 2024-02-09 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intranet', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('archivo_nomina', models.FileField(upload_to='archivos_nomina/')),
                ('num_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='num_empleado', to='intranet.empleados')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
            },
        ),
    ]
