# Generated by Django 4.2.6 on 2024-02-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH_Track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2024, verbose_name='Anio')),
                ('quincena', models.IntegerField(default=0, verbose_name='Quincena')),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Tabla de Nomina',
                'verbose_name_plural': 'Tabla de Nominas',
            },
        ),
        migrations.AlterModelOptions(
            name='nomina',
            options={'verbose_name': 'Nomina', 'verbose_name_plural': 'Nominas'},
        ),
    ]
