# Generated by Django 5.0.1 on 2024-02-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH_Track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2024, verbose_name='Año')),
                ('quincena', models.IntegerField(default=0, verbose_name='Quincena')),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Tabla de Nómina',
                'verbose_name_plural': 'Tabla de Nóminas',
            },
        ),
    ]
