# Generated by Django 4.2.3 on 2023-09-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codigo_almacen',
            fields=[
                ('id_almacen', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_almacen', models.CharField(default='', max_length=3, verbose_name='Codigo Almacen')),
                ('nombre_almacen', models.CharField(default='', max_length=250, verbose_name='Nombre Almacen')),
            ],
            options={
                'verbose_name': 'Codigo Almacen',
                'verbose_name_plural': 'Codigo Almacens',
            },
        ),
    ]
