# Generated by Django 4.2.3 on 2023-11-14 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('adjuntos_res', models.FileField(blank=True, null=True, upload_to='adjuntos/')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Mayer', 'Mayer Orozco'), ('Jonathan', 'Jonathan Castillo'), ('Oscar', 'Oscar Zermeño'), ('Jesus', 'Jesus Ibarra')], default='Mayer', max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('adjuntos', models.FileField(blank=True, null=True, upload_to='adjuntos/')),
                ('estatus', models.CharField(choices=[('Abierta', 'Abierta'), ('Esperando', 'Esperando su respuesta'), ('Resuelta', 'Resuelta')], default='Abierta', max_length=20)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('prioridad', models.CharField(blank=True, max_length=20, null=True)),
                ('respuestas_Tec', models.ManyToManyField(related_name='respuestas_ticket', to='tickets.respuesta')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.tecnico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.AddField(
            model_name='respuesta',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.tecnico'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='tickets.ticket'),
        ),
    ]
